### PR TITLE
Removing unused dependencies + adding automake reference to docs

### LINKED ISSUE #591: Check package.json of each individual project
Check commands
Check dependencies (npm install)

There is also an issue in the api project where "automate" lib is missing for Mac users - this should also be checked

### PR DESCRIPTION
**Pull request by galethil**
Removing unused dependencies from package.json

Closes #591

### CODE REVIEW

**Review by georgimld — CHANGES_REQUESTED** [review]
As mentioned in the chat, please edit the commit message (in this case, you can list all the projects you made changes to: "doc/api/ui: Remove unused packages" or something like this)

**Review by georgimld — APPROVED** [review]

**Comment by galethil** [comment]
Is there anything else needed to merge PR?

**Comment by georgimld** [comment]
> Is there anything else needed to merge PR?

No, the only thing left is to rebase the branch and push it again. However, I suggest waiting for the e2e tests to finish before merging, as they failed the last time (probably because of the backup test, which is now fixed)

**Comment by georgimld** [comment]
> > Is there anything else needed to merge PR?
> 
> No, the only thing left is to rebase the branch and push it again. However, I suggest waiting for the e2e tests to finish before merging, as they failed the last time (probably because of the backup test, which is now fixed)

And also please add a short description to the PR (e.g. what issue it closes)

**Review by georgimld — CHANGES_REQUESTED** [review]
correct the commits (rebase instead of merge)

**Review by georgimld — APPROVED** [review]

**Pull request merged**
