### PR TITLE
blockchain: Setup eslint and fix some errs

### LINKED ISSUE #675: Set up eslint for Blockchain module
- [ ] I have searched the [issues](https://github.com/openkfw/TruBudget/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by SamuelPull**
### Checklist

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/openkfw/TruBudget/blob/master/CONTRIBUTING.md).

### Description

This PR adds ESLint settings for blockchain module with similar rules and temporary overrides like in other modules.
PR adds required libraries to blockchain, `npm i` required.

PR contains a few fixes for some eslint errors. For example `arguments` in `blockchain/src/multichain-feed/email-notifications/sendNotifications.js` renamed to `args`, because `arguments`, as it turns out,  is a reserved keyword in JS.

Closes #675

### CODE REVIEW

**Comment by m-janos** [comment]
@SamuelPull I would like to know the reason why autofixable disabled rules cannot be applied right here.

**Comment by SamuelPull** [comment]
@m-janos Eslint config more or less copy-pasted from Provisioning. Reason for PR is the config, not fixes. I don't think there is a logical reason behind why certain rules are applied here and others not 😄

**Comment by m-janos** [comment]
> @m-janos Eslint config more or less copy-pasted from Provisioning. Reason for PR is the config, not fixes. I don't think there is a logical reason behind why certain rules are applied here and others not 😄

@SamuelPull thank for the clarification. It is good to know where to focus on

**Comment by m-janos** [comment]
@SamuelPull according Danger.js report. A record about those ESLint config changes in changelog is needed.

**Comment by SamuelPull** [comment]
@m-janos I don't think so, no mentions of eslint are in changelog.

**Comment by m-janos** [comment]
> @m-janos I don't think so, no mentions of eslint are in changelog.

@SamuelPull I know, it is weird. I will not push you into out-of-topic work.

**Review by m-janos — APPROVED** [review]

**Pull request merged**
