### PR TITLE
e2e: update test description workflowitem_edit_spec

### LINKED ISSUE #404: e2e: Write tests for workflowitem batch edit
### Description
There are no tests for the workflowitem batch edit feature. Other features could break it.

### Todo
Write e2e-tests:
- [x] Reordering of open workflowitems is done on submit
- [x] Reordering button is disabled when user has no permission or there are only closed workflowitems 
- [ ] "Reordering mode" is enabled but closed workflowitems can't  be reordered
- [ ] "Reordering mode" is enabled but workflowitems can't  be reordered if there are redacted ones in between
- [x] Batch edit drawer opens on selecting the first workflowitem in reordering mode
- [ ] Batch edit drawer views current permissions/assignee if they are the same
- [ ] Preview dialog opens on clicking the drawers update button
- [ ] Preview dialog shows right actions including revoking actions (because grant permissions via batch edit overwrites the permissions of a workflowitem)
- [x] Changes will be applied correctly
 
reference to #408

### PR DESCRIPTION
**Pull request by AsfaSamee**
### Description
 

In this pull request the script "workflowitem_edit_spec.js was updated". The new features are validated by additions in the test script. 

Note: The check of the rights of different users is missing. Two users were checked for this functionality mstein and root both have the same rights on e2e: Write tests for workflowitem batch edit . 
 

Closes #404

### CODE REVIEW

**Comment by AsfaSamee** [comment]
e2e: Write tests for workflowitem batch edit #404

**Comment by Stezido** [comment]
Changes have to be merged

**Review by Stezido — CHANGES_REQUESTED** [review]
Use the recommended vs code plugins (regarding format)
I would suggest to create an own file for batch editing workflowitems where tests like reordering workflowitems can also be located in.

**Comment by daniel-arnauer** [comment]
Tests are deprecated - #404 will be resolved in #546

**Pull request closed without merging**
